#!/usr/bin/env bash
set -euo pipefail
TARGET="${1:-.}"; LANGUAGE="${2:-en}"; DOMAIN="${3:-all}"; POLICY="${4:-ask}"; DRY_RUN="${5:-false}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; TARGET="$(cd "$TARGET" && pwd)"; SRC="$ROOT"; [[ "$LANGUAGE" == ko && -d "$ROOT/i18n/ko" ]] && SRC="$ROOT/i18n/ko"
case "$DOMAIN" in common) ;; llm) ;; vision) ;; all) ;; *) echo 'domain: common|llm|vision|all' >&2; exit 1;; esac
case "$POLICY" in ask|merge|overwrite|skip) ;; *) echo 'policy: ask|merge|overwrite|skip' >&2; exit 1;; esac
case "$DRY_RUN" in true|false) ;; *) echo 'dry_run: true|false' >&2; exit 1;; esac
files=(AGENTS.md CLAUDE.md GEMINI.md .github/copilot-instructions.md .github/instructions/llm.instructions.md .cursor/rules/coding-standard.mdc .windsurf/rules/coding-standard.md .clinerules/01-coding-standard.md .continue/rules/coding-standard.md .junie/AGENTS.md .amazonq/rules/coding-standard.md CONVENTIONS.md .aider.conf.yml COMMON/AGENT.md COMMON/SKILL.md COMMON/ENVIRONMENT.md)
[[ "$DOMAIN" == llm || "$DOMAIN" == all ]] && { files+=(LLM/AGENT.md LLM/SKILL.md LLM/ENVIRONMENT.md LLM/environment.py LLM/experiment.py LLM/memory_smoke_test.py LLM/README.md LLM/config/training.yaml LLM/config/ablation.yaml); while IFS= read -r f; do files+=("${f#$SRC/}"); done < <(find "$SRC/LLM/skills" -type f -name SKILL.md 2>/dev/null); }
[[ "$DOMAIN" == vision || "$DOMAIN" == all ]] && { files+=(VISION/AGENT.md VISION/SKILL.md VISION/ENVIRONMENT.md VISION/memory_smoke_test.py VISION/README.md VISION/config/training.yaml VISION/config/ablation.yaml); while IFS= read -r f; do files+=("${f#$SRC/}"); done < <(find "$SRC/VISION/skills" -type f -name SKILL.md 2>/dev/null); }
for rel in "${files[@]}"; do src="$SRC/$rel"; dst="$TARGET/$rel"; [[ -f "$src" ]] || { echo "Missing template: $rel" >&2; exit 1; }; if [[ "$DRY_RUN" == true ]]; then echo "[DRY-RUN] $([[ -e "$dst" ]] && echo EXIST || echo CREATE) $rel"; continue; fi; mkdir -p "$(dirname "$dst")"; if [[ ! -e "$dst" ]]; then cp "$src" "$dst"; continue; fi; action="$POLICY"; if [[ "$POLICY" == ask ]]; then read -r -p "Existing $rel [m]erge [o]verwrite [s]kip: " action; action="${action,,}"; fi; case "$action" in skip) ;; overwrite) cp "$src" "$dst" ;; merge) start='<!-- BEGIN CODINGSTANDARD MANAGED BLOCK -->'; end='<!-- END CODINGSTANDARD MANAGED BLOCK -->'; if [[ "$rel" =~ \.(py|ya?ml|sh|bash)$ ]]; then start='# BEGIN CODINGSTANDARD MANAGED BLOCK'; end='# END CODINGSTANDARD MANAGED BLOCK'; fi; incoming="$(cat "$src")"; if grep -Fq "$start" "$dst"; then awk -v s="$start" -v e="$end" -v n="$incoming" '$0==s{print;print n;in=1;next}$0==e{print;in=0;next}!in{print}' "$dst" > "$dst.tmp" && mv "$dst.tmp" "$dst"; else { cat "$dst"; printf '\n\n%s\n%s\n%s\n' "$start" "$incoming" "$end"; } > "$dst"; fi ;; *) echo 'Use merge, overwrite, or skip' >&2; exit 1;; esac; done
echo "Installed: language=$LANGUAGE domain=$DOMAIN dry_run=$DRY_RUN" 
